[prune]
  unused-packages = true
  non-go = true
  go-tests = true

[[constraint]]
  name = "github.com/mattermost/mattermost-server"
  version = "~5.1.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~1.2.0"
